import { Template } from "@pdfme/common";

export const reportTemplate: Template = { "schemas": [[{ "name": "title", "type": "multiVariableText", "content": "{}", "position": { "x": 10.59, "y": 20 }, "width": 105.56, "height": 6.8, "rotate": 0, "alignment": "left", "verticalAlignment": "top", "fontSize": 12, "lineHeight": 1, "characterSpacing": 0, "fontColor": "#1a3d7d", "fontName": "Roboto", "backgroundColor": "", "opacity": 1, "strikethrough": false, "underline": false, "readOnly": true, "text": "Reporte saldos físicos valorados", "variables": [], "required": false }, { "name": "subtitle", "type": "multiVariableText", "content": "{\"date\":\"29/01/2025\"}", "position": { "x": 86.72, "y": 27.23 }, "width": 105.56, "height": 6.8, "rotate": 0, "alignment": "center", "verticalAlignment": "middle", "fontSize": 12, "lineHeight": 1, "characterSpacing": 0, "fontColor": "#1a3d7d", "fontName": "Roboto", "backgroundColor": "", "opacity": 1, "strikethrough": false, "underline": false, "readOnly": false, "text": "Reporte de inventarios al {date}", "variables": ["date"], "required": false }, { "name": "table", "type": "table", "position": { "x": 10.259999999999991, "y": 35.45 }, "width": 258.74, "height": 19.7616, "content": "[[\"\",\"\",\"\",\"\",\"\",\"\"]]", "showHead": true, "head": ["NRO", "Productos", "Unidad", "Cantidad", "C.P.P", "Monto"], "headWidthPercentages": [5, 30, 20, 15, 15, 15], "tableStyles": { "borderWidth": 0.3, "borderColor": "#6b6b6b" }, "headStyles": { "fontName": "Roboto", "fontSize": 11, "characterSpacing": 0, "alignment": "left", "verticalAlignment": "middle", "lineHeight": 1, "fontColor": "#000000", "borderColor": "#6b6b6b", "backgroundColor": "#ffffff", "borderWidth": { "top": 0, "right": 0.1, "bottom": 0.3, "left": 0.1 }, "padding": { "top": 3, "right": 2, "bottom": 3, "left": 2 } }, "bodyStyles": { "fontName": "Roboto", "fontSize": 11, "characterSpacing": 0, "alignment": "left", "verticalAlignment": "middle", "lineHeight": 1, "fontColor": "#000000", "borderColor": "#6b6b6b", "backgroundColor": "", "alternateBackgroundColor": "#ffffff", "borderWidth": { "top": 0, "right": 0.1, "bottom": 0.1, "left": 0.1 }, "padding": { "top": 3, "right": 2, "bottom": 3, "left": 2 } }, "columnStyles": { "alignment": { "0": "left", "1": "left", "2": "left", "3": "left", "4": "left", "5": "left" } }, "required": false, "readOnly": false }, { "name": "total", "type": "multiVariableText", "content": "{\"total\":\"13\"}", "position": { "x": 90.82, "y": 58.1 }, "width": 97.36, "height": 15, "rotate": 0, "alignment": "center", "verticalAlignment": "middle", "fontSize": 12, "lineHeight": 1, "characterSpacing": 0, "fontColor": "#000000", "backgroundColor": "", "opacity": 1, "strikethrough": false, "underline": false, "readOnly": false, "text": "TOTAL:                                              {total}", "variables": ["total"], "required": false }]], "basePdf": { "width": 279, "height": 216, "padding": [20, 10, 20, 10] }, "pdfmeVersion": "5.3.1" }

export const kardexTemplate: Template = {
    "schemas": [
        [
            {
                "name": "title", "type": "multiVariableText", "content": "{\"element\":\"Exhibidor\"}", "position": { "x": 10.59, "y": 21 }, "width": 105.56, "height": 6.8, "rotate": 0, "alignment": "left", "verticalAlignment": "top", "fontSize": 12, "lineHeight": 1, "characterSpacing": 0, "fontColor": "#1a3d7d", "fontName": "Roboto", "backgroundColor": "", "opacity": 1, "strikethrough": false, "underline": false, "readOnly": false, "text": "Kardex físico valorado - {element}", "variables": ["element"], "required": false
            }, {
                "name": "table", "type": "table", "position": { "x": 10.259999999999991, "y": 30.69 }, "width": 258.74, "height": 13.7616,
                "content": "[]", "showHead": true,
                "head": ["DETALLE", "FECHA", "DOC", "CANTIDAD\nENTRADA", "P.U\nENTRADA", "IMPORTE\nENTRADA", "CANTIDAD\nSALIDA", "P.U\nSALIDA", "IMPORTE\nSALIDA", "SALDO\nCANTIDAD", "C.P.P", "SALDO\nIMPORTE"],
                "headWidthPercentages": [9, 9, 8, 8.5, 8, 8.5, 8.5, 8, 8, 8.5, 8, 8],
                "tableStyles": { "borderWidth": 0.3, "borderColor": "#6b6b6b" },
                "headStyles": { "fontName": "Roboto", "fontSize": 10, "characterSpacing": 0, "alignment": "left", "verticalAlignment": "middle", "lineHeight": 1, "fontColor": "#000000", "borderColor": "#6b6b6b", "backgroundColor": "#ffffff", "borderWidth": { "top": 0, "right": 0.1, "bottom": 0.3, "left": 0.1 }, "padding": { "top": 3, "right": 2, "bottom": 3, "left": 2 } },
                "bodyStyles": { "fontName": "Roboto", "fontSize": 10, "characterSpacing": 0, "alignment": "left", "verticalAlignment": "middle", "lineHeight": 1, "fontColor": "#000000", "borderColor": "#6b6b6b", "backgroundColor": "", "alternateBackgroundColor": "#ffffff", "borderWidth": { "top": 0, "right": 0.1, "bottom": 0.1, "left": 0.1 }, "padding": { "top": 3, "right": 2, "bottom": 3, "left": 2 } },
                "columnStyles": { "alignment": { "0": "left", "1": "left", "2": "left", "3": "left", "4": "left", "5": "left" } }, "required": false, "readOnly": false
            }
        ]
    ], "basePdf": { "width": 279, "height": 216, "padding": [20, 10, 20, 10] }, "pdfmeVersion": "5.3.1"
}

export const entriesReport: Template = {
    "schemas": [
        [
            {
                "name": "title", "type": "multiVariableText", "content": "{}", "position": { "x": 10.59, "y": 20 }, "width": 105.56, "height": 6.8, "rotate": 0, "alignment": "left", "verticalAlignment": "top", "fontSize": 12, "lineHeight": 1, "characterSpacing": 0, "fontColor": "#1a3d7d", "fontName": "Roboto", "backgroundColor": "", "opacity": 1, "strikethrough": false, "underline": false, "readOnly": true, "text": "Reporte entradas físicos valorados", "variables": [], "required": false
            }, {
                "name": "subtitle", "type": "multiVariableText", "content": "{\"date\":\"29/01/2025\"}", "position": { "x": 86.72, "y": 27.23 }, "width": 105.56, "height": 6.8, "rotate": 0, "alignment": "center", "verticalAlignment": "middle", "fontSize": 12, "lineHeight": 1, "characterSpacing": 0, "fontColor": "#1a3d7d", "fontName": "Roboto", "backgroundColor": "", "opacity": 1, "strikethrough": false, "underline": false, "readOnly": false, "text": "Reporte de inventarios al {date}", "variables": ["date"], "required": false
            }, {
                "name": "table", "type": "table", "position": { "x": 10, "y": 43.45 }, "width": 258.74, "height": 16.9392, "content": "[[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]]", "showHead": true, "head": ["DETALLE", "UNIDAD", "CANTIDAD", "IMPORTE", "CANTIDAD", "IMPORTE", "CANTIDAD", "IMPORTE", "CANTIDAD", "IMPORTE", "CANTIDAD", "IMPORTE", "CANTIDAD", "IMPORTE"], "headWidthPercentages": [10.95, 6.85, 6.85, 6.85, 6.85, 6.85, 6.85, 6.85, 6.85, 6.85, 6.85, 6.85, 6.85, 6.85], "tableStyles": { "borderWidth": 0.3, "borderColor": "#6b6b6b" }, "headStyles": { "fontName": "Roboto", "fontSize": 7, "characterSpacing": 0, "alignment": "left", "verticalAlignment": "middle", "lineHeight": 1, "fontColor": "#000000", "borderColor": "#6b6b6b", "backgroundColor": "#ffffff", "borderWidth": { "top": 0, "right": 0.2, "bottom": 0.3, "left": 0.2 }, "padding": { "top": 3, "right": 2, "bottom": 3, "left": 2 } }, "bodyStyles": { "fontName": "Roboto", "fontSize": 7, "characterSpacing": 0, "alignment": "left", "verticalAlignment": "middle", "lineHeight": 1, "fontColor": "#000000", "borderColor": "#6b6b6b", "backgroundColor": "", "alternateBackgroundColor": "#ffffff", "borderWidth": { "top": 0, "right": 0.2, "bottom": 0.2, "left": 0.2 }, "padding": { "top": 3, "right": 2, "bottom": 3, "left": 2 } }, "columnStyles": { "alignment": { "0": "left", "1": "left", "2": "left", "3": "left", "4": "left", "5": "left", "6": "left", "7": "left", "8": "left", "9": "left", "10": "left", "11": "left", "12": "left", "13": "left" } }, "required": false, "readOnly": false
            }, {
                "name": "table_header", "type": "table", "position": { "x": 10, "y": 35.45 }, "width": 258.74, "height": 8.4696, "content": "[]", "showHead": true, "head": ["", "", "SALDOS INICIALES", "RECIBIDO DE PRODUCCION", "COMPRA DE PROVEEDORES", "DEVUELTO DE CLIENTES", "AJUSTE INGRESOS", "TOTAL INGRESOS"], "headWidthPercentages": [10.95, 6.85, 13.7, 13.7, 13.7, 13.7, 13.7, 13.7], "tableStyles": { "borderWidth": 0.3, "borderColor": "#6b6b6b" }, "headStyles": { "fontName": "Roboto", "fontSize": 7, "characterSpacing": 0, "alignment": "center", "verticalAlignment": "middle", "lineHeight": 1, "fontColor": "#000000", "borderColor": "#6b6b6b", "backgroundColor": "#ffffff", "borderWidth": { "top": 0, "right": 0.2, "bottom": 0.3, "left": 0.2 }, "padding": { "top": 3, "right": 2, "bottom": 3, "left": 2 } }, "bodyStyles": { "fontName": "Roboto", "fontSize": 9, "characterSpacing": 0, "alignment": "left", "verticalAlignment": "middle", "lineHeight": 1, "fontColor": "#000000", "borderColor": "#6b6b6b", "backgroundColor": "", "alternateBackgroundColor": "#ffffff", "borderWidth": { "top": 0, "right": 0.2, "bottom": 0.2, "left": 0.2 }, "padding": { "top": 3, "right": 2, "bottom": 3, "left": 2 } }, "columnStyles": { "alignment": { "0": "left", "1": "left", "2": "center", "3": "center", "4": "center", "5": "center", "6": "center", "7": "center" } }, "required": false, "readOnly": true
            }
        ]
    ],
    "basePdf": { "width": 279, "height": 216, "padding": [20, 10, 20, 10] }, "pdfmeVersion": "5.3.1"
}

export const outputsReport: Template = {
    "schemas": [
        [
            {
                "name": "title", "type": "multiVariableText", "content": "{}", "position": { "x": 10.59, "y": 20 }, "width": 105.56, "height": 6.8, "rotate": 0, "alignment": "left", "verticalAlignment": "top", "fontSize": 12, "lineHeight": 1, "characterSpacing": 0, "fontColor": "#1a3d7d", "fontName": "Roboto", "backgroundColor": "", "opacity": 1, "strikethrough": false, "underline": false, "readOnly": true, "text": "Reporte salidas físicos valorados", "variables": [], "required": false
            }, {
                "name": "subtitle", "type": "multiVariableText", "content": "{\"date\":\"29/01/2025\"}", "position": { "x": 86.72, "y": 27.23 }, "width": 105.56, "height": 6.8, "rotate": 0, "alignment": "center", "verticalAlignment": "middle", "fontSize": 12, "lineHeight": 1, "characterSpacing": 0, "fontColor": "#1a3d7d", "fontName": "Roboto", "backgroundColor": "", "opacity": 1, "strikethrough": false, "underline": false, "readOnly": false, "text": "Reporte de inventarios al {date}", "variables": ["date"], "required": false
            }, {
                "name": "table", "type": "table", "position": { "x": 10, "y": 43.45 }, "width": 258.74, "height": 16.9392, "content": "[[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]]", "showHead": true, "head": ["DETALLE", "UNIDAD", "CANTIDAD", "IMPORTE", "CANTIDAD", "IMPORTE", "CANTIDAD", "IMPORTE", "CANTIDAD", "IMPORTE", "CANTIDAD", "IMPORTE"], "headWidthPercentages": [12.688296639629208, 7.937427578215529, 7.937427578215529, 7.937427578215529, 7.937427578215529, 7.937427578215529, 7.937427578215529, 7.937427578215529, 7.937427578215529, 7.937427578215529, 7.937427578215529, 7.937427578215529], "tableStyles": { "borderWidth": 0.3, "borderColor": "#6b6b6b" }, "headStyles": { "fontName": "Roboto", "fontSize": 7, "characterSpacing": 0, "alignment": "left", "verticalAlignment": "middle", "lineHeight": 1, "fontColor": "#000000", "borderColor": "#6b6b6b", "backgroundColor": "#ffffff", "borderWidth": { "top": 0, "right": 0.2, "bottom": 0.3, "left": 0.2 }, "padding": { "top": 3, "right": 2, "bottom": 3, "left": 2 } }, "bodyStyles": { "fontName": "Roboto", "fontSize": 7, "characterSpacing": 0, "alignment": "left", "verticalAlignment": "middle", "lineHeight": 1, "fontColor": "#000000", "borderColor": "#6b6b6b", "backgroundColor": "", "alternateBackgroundColor": "#ffffff", "borderWidth": { "top": 0, "right": 0.2, "bottom": 0.2, "left": 0.2 }, "padding": { "top": 3, "right": 2, "bottom": 3, "left": 2 } }, "columnStyles": { "alignment": { "0": "left", "1": "left", "2": "left", "3": "left", "4": "left", "5": "left", "6": "left", "7": "left", "8": "left", "9": "left", "10": "left", "11": "left", "12": "left", "13": "left" } }, "required": false, "readOnly": false
            }, {
                "name": "table_header", "type": "table", "position": { "x": 10, "y": 35.45 }, "width": 258.74, "height": 8.4696, "content": "[]", "showHead": true, "head": ["", "", "ENTREGADO A PRODUCCION", "VENDIDO", "PRESTADO", "AJUSTE SALIDAS", "TOTAL"], "headWidthPercentages": [12.6882966396292, 7.937427578215527, 15.874855156431053, 15.874855156431053, 15.874855156431053, 15.874855156431053, 15.874855156431053], "tableStyles": { "borderWidth": 0.3, "borderColor": "#6b6b6b" }, "headStyles": { "fontName": "Roboto", "fontSize": 7, "characterSpacing": 0, "alignment": "center", "verticalAlignment": "middle", "lineHeight": 1, "fontColor": "#000000", "borderColor": "#6b6b6b", "backgroundColor": "#ffffff", "borderWidth": { "top": 0, "right": 0.2, "bottom": 0.3, "left": 0.2 }, "padding": { "top": 3, "right": 2, "bottom": 3, "left": 2 } }, "bodyStyles": { "fontName": "Roboto", "fontSize": 9, "characterSpacing": 0, "alignment": "left", "verticalAlignment": "middle", "lineHeight": 1, "fontColor": "#000000", "borderColor": "#6b6b6b", "backgroundColor": "", "alternateBackgroundColor": "#ffffff", "borderWidth": { "top": 0, "right": 0.2, "bottom": 0.2, "left": 0.2 }, "padding": { "top": 3, "right": 2, "bottom": 3, "left": 2 } }, "columnStyles": { "alignment": { "0": "left", "1": "left", "2": "center", "3": "center", "4": "center", "5": "center", "6": "center", "7": "center" } }, "required": false, "readOnly": true
            }
        ]
    ],
    "basePdf": { "width": 279, "height": 216, "padding": [20, 10, 20, 10] }, "pdfmeVersion": "5.3.1"
}